// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDYIs6_8xOij1ptCttBOs-T2HAKnaCGJU',
    appId: '1:106496408829:web:0001a9a6eba9fcb538d294',
    messagingSenderId: '106496408829',
    projectId: 'jobfinder-eb6d1',
    authDomain: 'jobfinder-eb6d1.firebaseapp.com',
    storageBucket: 'jobfinder-eb6d1.appspot.com',
    measurementId: 'G-R1NK92SZK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15OYOSpCJRmNCDT-EN3EQnldhGWncg9Y',
    appId: '1:106496408829:android:f44385697fd839dc38d294',
    messagingSenderId: '106496408829',
    projectId: 'jobfinder-eb6d1',
    storageBucket: 'jobfinder-eb6d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjuBKh4yI651vdfkwrpLb5jHyWbi4Purg',
    appId: '1:106496408829:ios:93f85a093dfec44738d294',
    messagingSenderId: '106496408829',
    projectId: 'jobfinder-eb6d1',
    storageBucket: 'jobfinder-eb6d1.appspot.com',
    iosBundleId: 'com.fluttermine.fluttermine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjuBKh4yI651vdfkwrpLb5jHyWbi4Purg',
    appId: '1:106496408829:ios:1bf2928e9f356e9038d294',
    messagingSenderId: '106496408829',
    projectId: 'jobfinder-eb6d1',
    storageBucket: 'jobfinder-eb6d1.appspot.com',
    iosBundleId: 'com.fluttermine.fluttermine.RunnerTests',
  );
}
